Fixes for Merge Logic
usgs/neic-glass3 pull request #71
Opened 2020-09-09 17:59 UTC by jpatton-USGS

* **Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?**
This PR makes various changes to the duplicate hypocenter merging logic to improve detection performance. In addition it utilizes Zonestats for higher (more strict) nucleation thresholds in aseismic areas, and supports larger grids utilizing the thresholds of smaller grids if the smaller grids are within the larger grids.

2020-09-10 18:49 UTC, dkragness-usgs reviewed
Sorry, this is as far as I got.  I need to finish and then go back and resolve some of the comments that were for my own reference.

2020-09-10 18:49 UTC, dkragness-usgs commented on glasscore/glasslib/src/HypoList.cpp
> +	std::string primaryID = hypo->getID();
logic for this function:
```
Merge
  get list of possible hypos by time
  for each aHypo
    ensure aHypo is valid
    ensure aHypo is not (our) hypo
    try to lock it
      if can't lock, CONTINUE to next aHypo
    figure out fromHypo and intoHypo, based on external-publication and age
    ensure (again) fromHypo and intoHypo are valid
    log a whole bunch of info for the two hypos
    calculate distance between hypos 
      if distance is too far, CONTINUE to next aHypo
    resolveData() on intoHypo and fromHypo  - making sure their picks are singularly associated
    cancelCheck() intoHypo  - make sure it still has the minimum required number of picks
      if canceled, then removeHypo(), and merged = resolveRemoved = true
    cancelCheck() fromHypo  - make sure it still has the minimum required number of picks
      if canceled, then removeHypo(), and merged = resolveRemoved = true
    if resolveRemoved 
      if (our) hypo removed
        RETURN(true)  - DONE!
      else
        CONTINUE to next aHypo
    get intoPicks list of picks from intoHypo
    get fromPicks list of picks from fromHypo
    calculate intoBayes from post-Resolve intoHypo current bayes count
    calculate fromBayes from post-Resolve fromHypo current bayes count
    for each pick associated with fromHypo
      add pick to intoHypo
    anneal(intoHypo), - anneal does simulated-annealing location search and PICK PRUNING (slightly different than pruneData)
    pruneData(intoHypo)
      if pruned localize(intoHypo)
    newBayes = from post-merge/prune/localize intoHypo current bayes count
    if newBayes is significantly-better than intoBayes - MERGE SUCCESSFUL!
      set intoHypo creation time as min(intoHypo,fromHypo)
      removeHypo(fromHypo)
      merged = true
    else if newBayes better than intoBayes -
      resolveData(intoHypo)
        if resolved localize(intoHypo)
      localize(fromHypo) - Calculate bayes value (again?)
      resolveData(intoHypo)
         if resolved localize(intoHypo)
      cancelCheck() fromHypo  - make sure it still has the minimum required number of picks
        if canceled
          log stuff
            set intoHypo creation time as min(intoHypo,fromHypo)
            removeHypo(), and merged = resolveRemoved = true
            merged = true
      else  - fromHypo is still good (and intoHypo is not SIGNIFICANTLY better)
        log stuff
    else    - intoHypo is worse...   fake news!  fake news!  nothing to see here!
      log stuff
      clearPickReferences(intoHypo)
      for each pick in intoPicks - original pick list for intoHypo
        addPickReference(intoHypo, pick)
       localize(intoHypo)
      ignore fromHypo, leaving it in whatever state it's in...
    end if
  end for each aHypo
  RETURN(merged t/f)

```

2020-09-10 18:49 UTC, dkragness-usgs commented on glasscore/glasslib/src/HypoList.cpp
> +	if (resolveData(hyp)) {
should you cancelCheck() here?

2020-09-10 18:49 UTC, dkragness-usgs commented on glasscore/glasslib/src/Node.cpp
> +constexpr double CNode::k_residualDistanceAllowanceFactor;
I can't find the definition of this in the diff, so I'll add comment here.  Confused as to what a cubiod is, and exactly what this.  Is it a measurement or a flag?   1 is half the distance to the next node (center to edge), so the default of 2 is all the way to the next node(center)?

2020-09-10 18:49 UTC, dkragness-usgs commented on glasscore/glasslib/src/Node.cpp
> +			// skip this pick if it's not in the set of allowed sources
picks without source data are always included...
Seems like that deserves a behavior comment in the function header definition

2020-09-10 18:49 UTC, dkragness-usgs commented on glasscore/glasslib/src/Pick.cpp
> +constexpr double CPick::k_dMaxDepthAdjustFactor;
WTF?

2020-09-10 18:49 UTC, dkragness-usgs commented on glasscore/glasslib/src/Pick.cpp
> +	initialize(pickSite, pickTime, pickIdString, "", backAzimuth, slowness, "",
adding source as blank for this constructor.

2020-09-10 18:49 UTC, dkragness-usgs commented on glasscore/glasslib/src/Pick.cpp
> +
should there be another
```
else {
			source = "";
```
here?

2020-09-10 18:49 UTC, dkragness-usgs commented on glasscore/glasslib/src/Pick.cpp
> +		int ncut;
review got to here.

2020-09-10 22:59 UTC, dkragness-usgs reviewed
Done with review first pass.  Need to see if there are comments I can self-resolve.

2020-09-10 22:59 UTC, dkragness-usgs commented on glasscore/glasslib/src/Pick.cpp
> +			double maxDepth = 800.0;
magic number.  should be made into a constant class member...

2020-09-10 22:59 UTC, dkragness-usgs commented on glasscore/glasslib/src/Pick.cpp
> +		}
Add comment indicating what this brace is ending.

2020-09-10 22:59 UTC, dkragness-usgs commented on glasscore/glasslib/src/Pick.cpp
> +			if (trigger->getWeb()->getAllowControllingWebs() == true) {
meh...  I'm really not a fan of the whole controllingwebs deal.  Seems to make an assumption about picksets and an assumption about the regional web having a higher threshold than the web it's overriding.
This doesn't seem clean, and feels like the thing that's gonna bite someone the first time they try to setup a local grid that goes outside of your undocumented assumptions.

2020-09-10 22:59 UTC, dkragness-usgs commented on glasscore/glasslib/src/PickList.cpp
> +	while (m_PicksToProcessMutex.try_lock() == false) {
lines 141 - 163 look like a mess.
141 - 145 try to get a lock, so that the size of the queue can be read.
then lines 151 - 162 keep getting a lock until the size of the queue is small enough.

Why not write one loop that waits until a) a lock can be obtained, and b) the size is small enough?
  and then in 1 lock, it check's the size (re-try if size too big), and push()'s the pick.  That way we just lock ONCE, instead of THREE times.

2020-09-10 22:59 UTC, dkragness-usgs commented on glasscore/glasslib/src/PickList.cpp
> +	while (m_PicksToProcessMutex.try_lock() == false) {
You could even write a function called
lock_w_heartbeat(lock, sleep_duration, heartbeat_function, max_wait_duration) that handles all of it, and make the code more readable.

2020-09-10 22:59 UTC, dkragness-usgs commented on glasscore/glasslib/src/Web.cpp
> +			" nDetect:%d; nNucleate:%d; dThresh:%.2f; ASnNucleate:%d; ASdThresh:%.2f;"
It is beyond me why you can't add things to the end of the list instead of in the middle...

2020-09-10 22:59 UTC, dkragness-usgs commented on glasscore/glasslib/src/Web.cpp
> +				// get the network
bad cut & paste?   net/network should be source?
functionality is the same, but makes understanding teh code even MORE painful...

2020-09-10 22:59 UTC, dkragness-usgs commented on glasscore/glasslib/src/Web.cpp
> +	bool aSeismic = getZoneStatsAseismic(lat, lon);
This is not the right place for this comment, but why doesn't getZoneStatsAseismic() have a depth parameter and return true for hypocenter locations with non-aseismic epicenters that are outside of the zonestats depth range?

2020-09-10 22:59 UTC, dkragness-usgs commented on glasscore/glasslib/src/Web.cpp
> +		node->addSource(source);
do we expect to add so many sites in realtime that it's worth all the added space of storing pick-source info at the node level?

2020-09-10 22:59 UTC, dkragness-usgs commented on glasscore/glasslib/src/Web.cpp
> +	if (m_pZoneStats == NULL) {
I think we should add depth to this function, and potentially return aseismic for aseismic depths of seismic epicenters.  Might fix the Indiana problem.

2020-09-10 22:59 UTC, dkragness-usgs commented on glasscore/glasslib/src/Web.cpp
> +		return(m_dWidth * m_dHeight);
What's the idea here?  rank by overall size of the web, with the expectation that larger webs are more general and supersedable, as opposed to rank by web-granularity (using inter-node distance as a proxy)

2020-09-10 22:59 UTC, dkragness-usgs commented on glasscore/tests/hypo_unittest.cpp
> +#define TRIGGER_ASEISMIC false
not gonna code-review the unit tests.  Gonna assume they are better tested than reviewed.

2020-09-10 22:59 UTC, dkragness-usgs commented on glasscore/traveltime/tt-files/zonestats_M3.5_2010_2020.txt
> +#﻿# -*- coding: utf-8 -*-
This file is HOSED!  DO NOT USE!!! 
Min/Max Depths are always the same.  Who wrote the code to generate this anyway!?!  It should've been code reviewed! ;-)

2020-09-10 22:59 UTC, dkragness-usgs commented on util/include/threadpool.h
>  	 * seconds between status checks. -1 to disable status checks.  Default 30.
Default was changed to 300.  don't forget to update the comment ;)

2020-09-10 22:59 UTC, dkragness-usgs commented on util/src/threadbaseclass.cpp
> +	int lastCheckInterval = (std::time(nullptr) - getAllLastHealthy(&thread_id));
this isn't the lastCheck, it's more time-since-all-last-healthy

lastCheckInterval makes it sound like this is the last time you checked, not the last time everything was copacetic, er, uh..., good!

2020-09-11 04:18 UTC, dkragness-usgs commented on glasscore/glasslib/include/Hypo.h
> +	 * \param parentThread - A pointer to a parent Hypolist thread to
This is for issuing call-out heartbeats during long-running functions that are not part of the original class that is being monitored.

2020-09-11 04:19 UTC, dkragness-usgs commented on glasscore/glasslib/include/Hypo.h
> +			CHypoList* parentThread = NULL);
Hard for me to believe that resolveData() can't execute in 30 seconds, let alone 300.  Seems like someone was losing their mind over restarts and went hog wild!

2020-09-11 04:20 UTC, dkragness-usgs commented on glasscore/glasslib/include/HypoList.h
> +		CPickList* parentThread = NULL);
again, hard to believe this is necessary.  Something's wrong if it takes 30 seconds to add a hypo, let alone 5 minutes...

2020-09-11 04:21 UTC, dkragness-usgs commented on glasscore/glasslib/include/Node.h
> +	 * \param aseismic - A boolean flag indicating whether this node is in an
Leaving this open till you see it, but you can close it.

2020-09-11 04:23 UTC, dkragness-usgs commented on glasscore/glasslib/include/Node.h
> +	void addSource(std::string source);
or something that syas see CNode::m_SourceSet for description / example of a source, although seems better practice to document it in the public section of the header, which would be the definition for  this function.

2020-09-11 04:44 UTC, dkragness-usgs requested changes
I resolved a bunch of my comments, but left plenty of sass and requests for the  PR author.
Please see comment and resolve as you see fit.  There are lots of things that I'm not happy about, but on your side of the argument you have proof that the code mostly works well and probably a huge load of other ToDo's just screaming for your attention.

2020-09-11 04:44 UTC, dkragness-usgs commented on glasscore/glasslib/include/Pick.h
> +					std::string pickIdString, std::string source,
I want you to witness my pain... THEN you can close this.

2020-09-11 04:44 UTC, dkragness-usgs commented on glasscore/glasslib/include/Web.h
> +	 * \param allowControllingWebs - A boolean flag indicating whether this web
meh.... :shakes_head_and_wanders_off...

2020-09-11 04:44 UTC, dkragness-usgs commented on glasscore/glasslib/include/WebList.h
> +	 * This function returns the controlling web based on the provided coordinates
Somewhere else I remember reading that if there's a tie, NULL is returned.  Seems like that should be written here, or that description should be linked to from here.

2020-09-11 04:44 UTC, dkragness-usgs commented on glasscore/glasslib/src/Hypo.cpp
> +											m_tOrigin, false));
I'm referring to the last param to calculateBayes() which was added as part of this PR/MR/VR experience.

2020-09-11 04:44 UTC, dkragness-usgs commented on glasscore/glasslib/src/Hypo.cpp
>  		if (m_pTravelTimeTables->m_bPublishable == false) {
To me, this reads like, are the traveltimes publishable, which is a real head-scratcher...
I think it should read, is the current phase publishable, since i think you guys added something for tracked, but non-published phases.   
I kept expecting to see more on this in the MR, but didn't find anything further.
Head scratcher...

2020-09-11 04:44 UTC, dkragness-usgs commented on glasscore/glasslib/src/Hypo.cpp
> +			parentThread->setThreadHealth();
yeah, this every-other-line is parentThread->setThreadHealth()  seems f'd up and desperate, which are two things you don't mind seeing in an alcoholic beverage salesman, but not good for the code that is the underpinning of earthquake detection for the national system.

2020-09-11 04:44 UTC, dkragness-usgs commented on glasscore/glasslib/src/HypoList.cpp
> +						if (aHypo->addPickReference(pick) == true) {
If I have to write comments to myself while reviewing the diff, it's a likely indication that the code author didn't write enough meaningful ones....

2020-09-11 04:44 UTC, dkragness-usgs commented on glasscore/glasslib/src/HypoList.cpp
> +	if (resolveData(hyp)) {
maybe write that workflow into a comment at the top, so that people can quickly pick up on it, instead of having to use the long code read, with lots of interruptive logging and cleanup statements.

2020-09-11 04:44 UTC, dkragness-usgs commented on glasscore/glasslib/src/Node.cpp
> +			// skip this pick if it's not in the set of allowed sources
I get why it's done, but seems like it at least deserves to register as a comment.

2020-09-11 04:44 UTC, dkragness-usgs commented on glasscore/glasslib/src/Web.cpp
> +			" nDetect:%d; nNucleate:%d; dThresh:%.2f; ASnNucleate:%d; ASdThresh:%.2f;"
nothing to see or do here, other than to feel my pain...

2020-09-11 04:44 UTC, dkragness-usgs commented on glasscore/tests/hypo_unittest.cpp
> +#define TRIGGER_ASEISMIC false
want you to see this comment, in case you object.  Once you've seen it, you can resolve it, or complain about it, or both.

2020-09-11 04:44 UTC, dkragness-usgs commented on util/include/threadpool.h
>  	 * seconds between status checks. -1 to disable status checks.  Default 30.
300 seems a bit much, especially with your upteen-million setParentHealth() calls (or whatever they're called).
Hard to believe you could tie up for 3 seconds during normal processing, let alone 30 or 300, but clearly you have some scars from some point in a debugging cycle.

2020-09-11 14:06 UTC, jpatton-USGS commented on glasscore/glasslib/include/Hypo.h
> +			CHypoList* parentThread = NULL);
So I have observed a couple glass exits where one of the picklist threads (based on the logs) times out and exits. All of this parent stuff is me trying to find that timeout problem and fix it.

2020-09-11 14:09 UTC, jpatton-USGS commented on glasscore/glasslib/include/Pick.h
> +					std::string pickIdString, std::string source,
it made sense to put it there.

2020-09-11 14:10 UTC, jpatton-USGS commented on glasscore/glasslib/include/Node.h
> +	void addSource(std::string source);
k

2020-09-11 14:11 UTC, jpatton-USGS commented on glasscore/glasslib/include/Pick.h
> +	static constexpr double k_dMaxDepthAdjustFactor = 10;
I can do one better, I can remove it because it's unused

2020-09-11 14:12 UTC, jpatton-USGS commented on glasscore/glasslib/include/Trigger.h
> +				double maxZ, double sum, int count, bool aSeismic,
Yes, Caryl originally just passed the node around, but that meant the node was locked until the trigger was rejected or confirmed, which seemed far to long, instead the relevant information from the node is copied into the trigger object, and the node can go on and do it's thing

2020-09-11 14:20 UTC, jpatton-USGS commented on glasscore/glasslib/include/Trigger.h
> +	CWeb* getWeb();
was part of an attempt to get a shared pointer further down the line, reverted

2020-09-11 14:26 UTC, jpatton-USGS commented on glasscore/glasslib/src/Hypo.cpp
> +		return (generateCancelMessage());
a cancel message will only result in a retraction if the output code 1. has the event (it hasn't already been canceled) and 2. It's already been published by output.

2020-09-11 14:31 UTC, jpatton-USGS commented on glasscore/glasslib/src/Hypo.cpp
>  		if (m_pTravelTimeTables->m_bPublishable == false) {
m_bPublishable is set in the above m_pTravelTimeTables->T() call, a bit of a leftover from Caryl's ttt design.

2020-09-11 14:34 UTC, jpatton-USGS commented on glasscore/glasslib/src/HypoList.cpp
> +			hypo->getTOrigin() - (k_dExistingTimeTolerance * 0.55),
I didn't want to do +/- just 1/2 the time window because of edge cases, so I did +/- a little more than 1/2

2020-09-11 14:37 UTC, jpatton-USGS commented on glasscore/glasslib/src/HypoList.cpp
> +			if (std::shared_ptr<CHypo> aHypo = hypoList[i].lock()) {
it's not an iterator, it's a shared ptr generated from locking a weak_ptr from a vector of weak_ptr's

2020-09-11 14:37 UTC, dkragness-usgs commented on glasscore/glasslib/include/Hypo.h
> +			CHypoList* parentThread = NULL);
if you were trying to find it, you would log the function that you were in as part of the heartbeat, or at least that's what I would do.

2020-09-11 14:40 UTC, jpatton-USGS commented on glasscore/glasslib/src/HypoList.cpp
> +		breport = true;
send summary of hypo out of glasscore to the output code

2020-09-11 14:41 UTC, dkragness-usgs commented on glasscore/glasslib/include/Trigger.h
> +				double maxZ, double sum, int count, bool aSeismic,
Why does the Node have to be locked?  Are Nodes changing in realtime?  Yes, because of station additions?  Do the readers really need to lock the node?  Can't they have a semaphore instead of an exclusive lock?  Seems like station updates don't need to move with the speed of light?

2020-09-11 14:42 UTC, jpatton-USGS commented on glasscore/glasslib/src/HypoList.cpp
> +		// they're not sharing picks.
@wyeck-usgs

2020-09-11 14:43 UTC, dkragness-usgs commented on glasscore/glasslib/src/Hypo.cpp
>  		if (m_pTravelTimeTables->m_bPublishable == false) {
I still don't get it, but probably more important that I can complain it looks stupid than to actually do something about it.  Is there some sort of description of m_bPublishable and its use, in its definition?

2020-09-11 14:45 UTC, dkragness-usgs commented on glasscore/glasslib/src/HypoList.cpp
> +			hypo->getTOrigin() - (k_dExistingTimeTolerance * 0.55),
seems like you should be pulling +/- the WHOLE time window.  Especially since you have evaluations below that use the WHOLE time window.

2020-09-11 14:45 UTC, jpatton-USGS commented on glasscore/glasslib/src/HypoList.cpp
> +		if ((intoHypo->getID() == "") || (fromHypo->getID() == "")) {
we checked BEFORE we had a lock, in the time between the first check and getting the lock, the event could have been nuked.

2020-09-11 14:46 UTC, jpatton-USGS commented on glasscore/glasslib/src/HypoList.cpp
> +	if (resolveData(hyp)) {
It's already done in generateHypoMessage

2020-09-11 14:47 UTC, dkragness-usgs commented on glasscore/glasslib/src/HypoList.cpp
> +			if (std::shared_ptr<CHypo> aHypo = hypoList[i].lock()) {
potato potahto...  it's a temporary pointer you're using to iterate through a list...

2020-09-11 14:50 UTC, jpatton-USGS commented on glasscore/glasslib/src/Pick.cpp
> +
No, because source is initialized to "". std::string source = "";

2020-09-11 14:59 UTC, jpatton-USGS commented on glasscore/glasslib/src/Web.cpp
> +		node->addSource(source);
eh?

2020-09-11 14:59 UTC, jpatton-USGS commented on glasscore/glasslib/src/Web.cpp
> +	if (m_pZoneStats == NULL) {
@wyeck-usgs

2020-09-11 14:59 UTC, jpatton-USGS commented on glasscore/glasslib/src/Web.cpp
> +		return(m_dWidth * m_dHeight);
Yes, larger webs are expected to be more general

2020-09-11 15:00 UTC, jpatton-USGS commented on glasscore/traveltime/tt-files/zonestats_M3.5_2010_2020.txt
> +#﻿# -*- coding: utf-8 -*-
@wyeck-usgs

2020-09-11 15:01 UTC, dkragness-usgs commented on glasscore/glasslib/src/Web.cpp
> +	bool aSeismic = getZoneStatsAseismic(lat, lon);
I can't imagine who would give such a narrow minded directive.

2020-09-11 15:02 UTC, jpatton-USGS commented on util/include/threadpool.h
>  	 * seconds between status checks. -1 to disable status checks.  Default 30.
Threadpool doesn't do health checks, given it just calls the function pointer thingy and waits until it's done, then reports healthy. If you get into some resource contention, say file system isn't writable for a bit due to a virus scanner scanning, the whole thing exits.

2020-09-11 15:45 UTC, wyeck-usgs commented on glasscore/glasslib/src/Web.cpp
> +		return(m_dWidth * m_dHeight);
This feature can be turned on and off right?

2020-09-11 15:47 UTC, wyeck-usgs commented on glasscore/traveltime/tt-files/zonestats_M3.5_2010_2020.txt
> +#﻿# -*- coding: utf-8 -*-
I'll update this. Is min even used? We tried to get this in original DK format, but it wouldn't be better to have an easier interpret format?  Maybe not worth the effort.

2020-09-11 16:06 UTC, jpatton-USGS commented on glasscore/glasslib/include/HypoList.h
> +	static constexpr double k_dExistingTimeTolerance = 5.0;
no

2020-09-11 16:10 UTC, jpatton-USGS commented on glasscore/glasslib/include/Trigger.h
> +				double maxZ, double sum, int count, bool aSeismic,
The node maintains a vector of picks that support nucleation at that node, in order to keep that consistant, the node stays locked (can't nucleate again, which would wipe that vector) until the trigger is confirmed (turned into a hypo) or rejected. In caryl's single threaded world this all was easy, in multithreading, it made sense to copy the node parameters + pick vector into a seperate object so the node could move on.

2020-09-11 16:13 UTC, jpatton-USGS commented on glasscore/glasslib/src/Hypo.cpp
>  		if (m_pTravelTimeTables->m_bPublishable == false) {
The publishable stuff was largely handed in an earlier (already merge) PR, I think you're commenting on a minor formatting tweak I did.

2020-09-11 16:15 UTC, jpatton-USGS commented on glasscore/glasslib/src/HypoList.cpp
> +			if (std::shared_ptr<CHypo> aHypo = hypoList[i].lock()) {
no, it's a pointer to the object I'm evaluating, the closest thing to an iterator here is hypoList

2020-09-11 16:17 UTC, jpatton-USGS commented on glasscore/glasslib/src/Web.cpp
> +		return(m_dWidth * m_dHeight);
Yes, it's only configured for global grids

2020-09-11 17:05 UTC, dkragness-usgs commented on glasscore/glasslib/include/Trigger.h
> +				double maxZ, double sum, int count, bool aSeismic,
meh...  I don't think that's the way I would've done it, but none of this seems that relevant to this PR.  Moving on...

2020-09-11 17:07 UTC, dkragness-usgs commented on glasscore/glasslib/include/Web.h
> +	 * \param numASeismicNucleate = An optional integer value containing the
still doesn't seem to say "aseismic" in the comment.

2020-09-11 17:09 UTC, dkragness-usgs commented on glasscore/glasslib/src/HypoList.cpp
> +			hypo->getTOrigin() - (k_dExistingTimeTolerance * 0.55),
I stand by my most recent comment

2020-09-11 17:10 UTC, dkragness-usgs commented on glasscore/glasslib/src/HypoList.cpp
> +			if (std::shared_ptr<CHypo> aHypo = hypoList[i].lock()) {
hypoList is the array, not the iterator...   :throws_hands_up_in_the_air_and_sighs....

2020-09-11 17:11 UTC, dkragness-usgs commented on glasscore/glasslib/src/HypoList.cpp
> +		breport = true;
if you're making other changes, can you please add "send summary of hypo out of glasscore to the output code and other listeners inside g3"  or something like that to the comments.

2020-09-11 17:13 UTC, dkragness-usgs commented on glasscore/glasslib/src/HypoList.cpp
> +		if ((intoHypo->getID() == "") || (fromHypo->getID() == "")) {
seems redundant to check twice, but not gonna destroy the free world....

2020-09-11 17:16 UTC, dkragness-usgs commented on glasscore/glasslib/src/Pick.cpp
> +
then why do you set source = "" in the else above.   You can't have it both ways...

2020-09-11 17:17 UTC, dkragness-usgs commented on glasscore/glasslib/src/Web.cpp
> +	bool aSeismic = getZoneStatsAseismic(lat, lon);
@wyeck-usgs

2020-09-11 17:18 UTC, dkragness-usgs commented on glasscore/glasslib/src/Web.cpp
> +		node->addSource(source);
as opposed to storing it at the web level.

2020-09-11 17:20 UTC, jpatton-USGS commented on glasscore/glasslib/src/HypoList.cpp
> +			hypo->getTOrigin() - (k_dExistingTimeTolerance * 0.55),
k fine

2020-09-11 17:22 UTC, dkragness-usgs commented on glasscore/glasslib/src/Web.cpp
> +		return(m_dWidth * m_dHeight);
> * \return Returns a double value the relative size of the web
I don't understand that.
I understand "returns the overall size of the web (lat deg * lon deg)"

2020-09-11 17:22 UTC, jpatton-USGS commented on glasscore/glasslib/src/HypoList.cpp
> +		breport = true;
that's really covered below here where breport is checked, I'll add some comments there.

2020-09-11 17:23 UTC, jpatton-USGS commented on glasscore/glasslib/src/HypoList.cpp
> +	if (resolveData(hyp)) {
k

2020-09-11 17:24 UTC, jpatton-USGS commented on glasscore/glasslib/src/Pick.cpp
> +
I totally can

2020-09-11 17:40 UTC, wyeck-usgs commented on glasscore/glasslib/src/HypoList.cpp
> +		// they're not sharing picks.
I don't think this is a significant issue and it is tricky because of the chaotic nature of the algorithm and that events are not exactly stable. You would hope that the "from" hypo is stable because has recently gone through processHypo. The "to" Hypo has been localized again, but picks have not been pruned (that step is after this merge step in processHypo). I think if this issue occurred, it would be resolved during another merge attempt. That said, I see no issue in pruning both events here, so we might as well.

2020-09-11 17:50 UTC, jpatton-USGS commented on glasscore/glasslib/src/HypoList.cpp
> +		// they're not sharing picks.
k

2020-09-11 17:59 UTC, wyeck-usgs commented on glasscore/glasslib/src/HypoList.cpp
> +		intoHypo->anneal(
I don't think so, but maybe we could call localize here. Anneal originally was the first pass locator used to assign arrivals and phase types to an event when it is attempting to nucleate. Originally it was only called by pick.cpp when a pick was trying to nucleate an event. It attempts to locate the event, using only the nucleation branches (just P or P and S usually), then it goes through the picks to see which have a small enough residual to belong to the event. This is all prior to the hypocenter being considered valid and being added to the list. I think the function is fine as is. 

I think I chose to use anneal here because in my mind, we were creating a new hypo so I was following the same procedures as nucleation. Really though we know that these are good (enough) events at this points, so why no just run the normal localize? Do you see any issue with that? Then it will be more of an apples to apples comparison because all travel-time branches will be considered and the bayes value will be most comparable.

2020-09-11 18:08 UTC, dkragness-usgs commented on glasscore/glasslib/src/HypoList.cpp
> +		intoHypo->anneal(
apples to apples is what I was going for.  For the purposes of this function, I think that's the important part.  We judge success by the before and after bayes values, and so we want the before processing of the intoHypo to match the merge processing.
Do we then need to call pruneData() separately on the intoHypo after merge for it to be fair?

2020-09-11 18:31 UTC, dkragness-usgs commented on glasscore/glasslib/src/Web.cpp
> +	bool aSeismic = getZoneStatsAseismic(lat, lon);
This function is called while building nodes.  The Web's logic already uses zonestats to not build nodes at aseismic depths  via calls to m_pZoneStats->getMaxDepthForLatLon()

2020-09-11 18:33 UTC, dkragness-usgs commented on glasscore/glasslib/src/Web.cpp
> +	if (m_pZoneStats == NULL) {
@wyeck-usgs says this is already handled to his satisfaction via m_pZoneStats->getMaxDepthForLatLon() that's called when deciding what Nodes to build.

2020-09-11 19:49 UTC, dkragness-usgs commented on glasscore/traveltime/tt-files/zonestats_M3.5_2010_2020.txt
> +#﻿# -*- coding: utf-8 -*-
much better.

2020-09-11 19:50 UTC, merged